name: Rust

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose   
    - name: Generate Documentation
      run: |
        cargo doc
    - name: Archive Documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: target/doc
    - name: Display Documentation URL
      run: echo "Documentation is available as an artifact at ${{ steps.archive_documentation.outputs.artifact_url }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Documentation Artifact
      uses: actions/download-artifact@v2
      with:
        name: documentation
        path: ./public
    - name: Display structure of downloaded files
      run: ls -R
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
